name: TempCompareScreenshot

on:
  workflow_dispatch:

jobs:
  compare-screenshot-test:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:

      - uses: dawidd6/action-download-artifact@v2
        continue-on-error: true
        with:
          name: test-upload_artifact
          workflow: TempStoreScreenshot.yml
          branch: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.ref || github.event.repository.default_branch }}

      - name: Show
        run: |
          pwd
          ls ../
          ls ../..
          ls -la
          ls -la f1
          ls -la f2
          ls -la f1/build
          ls -la f2/build
          cat f1/build/hello.txt
          cat f2/build/hello.txt