name: TempStoreScreenshot

on:
  push:
    branches:
      - main

jobs:
  store-screenshot-test:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:

      - name: Create Hello
        run: |
          mkdir -p f1
          mkdir -p f2
          echo Hello World1 > f1/hello.txt
          echo Hello World2 > f2/hello.txt

      - uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: test-upload_artifact
          path: |
            hello.txt
          retention-days: 30